import 'dart:io';
import 'dart:typed_data';

import 'package:sofabuffers/sofabuffers.dart' as sofab;
import 'package:test/test.dart';

import 'vector_support.dart';

/// Drives the shared, language-agnostic conformance suite
/// (`assets/test_vectors.json`, generated by and copied from `corelib-c-cpp`).
///
/// This port supports the full wire format (no feature-disable), so per the
/// vectors README it **ignores `requires` and runs every vector**.
void main() {
  final root =
      decodeVectorJson(File('assets/test_vectors.json').readAsStringSync())
          as Map;

  final vectors = (root['vectors'] as List).cast<Map<String, dynamic>>();

  test('vector file metadata', () {
    expect(root['format'], 'sofabuffers-test-vectors');
    expect(jInt(root['version']), 1);
    expect(vectors, isNotEmpty);
  });

  group('vectors', () {
    for (final v in vectors) {
      final name = v['name'] as String;
      final group = v['group'] as String;
      final offset = jInt(v['offset']);
      final fields = v['fields'] as List<dynamic>;
      final expectedHex = (v['serialized'] as Map)['hex'] as String;
      final skipIds = ((v['skip_ids'] as List?) ?? const []).map(jInt).toSet();

      // 1. Vector encode — replay fields, assert bytes == serialized.hex.
      test('$group/$name · encode', () {
        final bytes = encodeFields(fields, offset: offset);
        expect(bytesToHex(bytes), expectedHex);
      });

      // Chunked encode — a buffer far smaller than the message, driving the
      // flush callback repeatedly; concatenated output must match one-shot.
      test('$group/$name · chunked-encode', () {
        for (final bufSize in const [1, 3, 7]) {
          final out = BytesBuilder(copy: true);
          final enc = sofab.Encoder(out.add, bufferSize: bufSize);
          replay(enc, fields);
          enc.flush();
          expect(
            bytesToHex(out.toBytes()),
            expectedHex,
            reason: 'bufSize=$bufSize',
          );
        }
      });

      // 2. Vector decode — feed serialized.hex, assert recovered fields match.
      test('$group/$name · decode', () {
        final rec = RecordingVisitor();
        final status = sofab.Decoder.decode(hexToBytes(expectedHex), rec);
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // Chunked decode — one byte at a time must equal all-at-once.
      test('$group/$name · chunked-decode', () {
        final bytes = hexToBytes(expectedHex);
        final rec = RecordingVisitor();
        final dec = sofab.Decoder(rec);
        var status = sofab.DecodeStatus.complete;
        for (final b in bytes) {
          status = dec.feed([b]);
        }
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // 3. Roundtrip — encode → decode → compare.
      test('$group/$name · roundtrip', () {
        final bytes = encodeFields(fields);
        final rec = RecordingVisitor();
        final status = sofab.Decoder.decode(bytes, rec);
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // Skip-ids — leave the named ids unread at every level; the rest must
      // still decode and the message must be fully consumed.
      if (skipIds.isNotEmpty) {
        test('$group/$name · skip-ids', () {
          final rec = RecordingVisitor(skipIds: skipIds);
          final status = sofab.Decoder.decode(hexToBytes(expectedHex), rec);
          expect(status, sofab.DecodeStatus.complete);
          expect(rec.events, expectedEventsSkipping(fields, skipIds));
        });

        test('$group/$name · skip-ids chunked', () {
          final bytes = hexToBytes(expectedHex);
          final rec = RecordingVisitor(skipIds: skipIds);
          final dec = sofab.Decoder(rec);
          var status = sofab.DecodeStatus.complete;
          for (final b in bytes) {
            status = dec.feed([b]);
          }
          expect(status, sofab.DecodeStatus.complete);
          expect(rec.events, expectedEventsSkipping(fields, skipIds));
        });
      }
    }
  });
}

/// Replays a vector's `fields` through an existing encoder (for the chunked
/// path, where we drive the streaming API directly rather than the one-shot
/// convenience).
void replay(sofab.Encoder e, List<dynamic> fields) {
  for (final f in fields.cast<Map<String, dynamic>>()) {
    switch (f['op'] as String) {
      case 'unsigned':
        e.writeUnsigned(jInt(f['id']), jU(f['value']));
        break;
      case 'signed':
        e.writeSigned(jInt(f['id']), jU(f['value']));
        break;
      case 'boolean':
        e.writeBool(jInt(f['id']), f['value'] as bool);
        break;
      case 'fp32':
        e.writeFp32(jInt(f['id']), jF(f['value']));
        break;
      case 'fp64':
        e.writeFp64(jInt(f['id']), jF(f['value']));
        break;
      case 'string':
        e.writeString(jInt(f['id']), f['value'] as String);
        break;
      case 'blob':
        e.writeBlob(jInt(f['id']), hexToBytes(f['value_hex'] as String));
        break;
      case 'array':
        final id = jInt(f['id']);
        final et = f['element_type'] as String;
        final values = f['values'] as List<dynamic>;
        if (et == 'fp32') {
          e.writeFp32Array(id, values.map(jF).toList());
        } else if (et == 'fp64') {
          e.writeFp64Array(id, values.map(jF).toList());
        } else if (et.startsWith('u')) {
          e.writeUnsignedArray(id, values.map(jU).toList());
        } else {
          e.writeSignedArray(id, values.map(jU).toList());
        }
        break;
      case 'sequence_begin':
        e.beginSequence(jInt(f['id']));
        break;
      case 'sequence_end':
        e.endSequence();
        break;
    }
  }
}
