import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:sofa_buffers_corelib/sofa_buffers_corelib.dart' as sofab;
import 'package:test/test.dart';

import 'vector_support.dart';

/// Drives the shared, language-agnostic conformance suite
/// (`assets/test_vectors.json`, generated by and copied from `corelib-c-cpp`).
///
/// This port supports the full wire format (no feature-disable), so per the
/// vectors README it **runs every vector**: its `requires` sets are all
/// satisfied by the single profile this repo builds. That is asserted rather
/// than assumed — [_supportedCapabilities] below is checked against every
/// `requires` token in the file, so a vector needing a capability this port
/// does not implement fails the suite instead of being silently run anyway.
///
/// **Which column this repo asserts:** every check below uses `serialized` —
/// the dense, primitive-layer ground truth: exactly the bytes the raw
/// encoder/decoder API produces and consumes for the vector's op list. Each
/// vector also carries a `serialized_sparse` column, and **no test here reads
/// it, by design**: it is the MESSAGE_SPEC §2 sparse form, which only a message
/// layer can produce — the layer that knows each field's declared default and
/// therefore which fields (and which all-default sequences) to omit. A corelib
/// has no message layer; it is handed ops and writes them. `serialized_sparse`
/// is consumed by the **generator's** conformance drivers
/// (`tests/conformance/<lang>/` in `sofa-buffers/generator`), which generate a
/// message layer from the schema and compare its output against that column.
/// The wire-format capabilities this port implements, in the vocabulary the
/// vectors' `requires` sets use. Dart builds one profile with no feature
/// switches, so this is the complete list — every vector is runnable, and the
/// suite proves that by rejecting a `requires` token that is not in here.
const Set<String> _supportedCapabilities = {
  'int64',
  'fixlen',
  'fp64',
  'array',
  'sequence',
};

/// The sizes the current vector file is known to contain (corelib-c-cpp#160).
///
/// Nothing in this loader is fixed-size — `skip_ids`, payloads, element lists
/// and ids all arrive as `jsonDecode`'s growable `List`s and Dart `int`s — but
/// "there is no cap" is only worth as much as a test that would notice one.
/// These floors are that test: they assert the suite really saw the big cases
/// the skip matrix needs, so a loader that ever started truncating (or a stale
/// asset) fails loudly here instead of quietly testing less.
const int _minSkipIdsPerVector = 9; // longest `skip_ids` list
const int _minFieldId = 100001; // three-byte header varint
const int _minArrayElements = 130; // two-byte element count
const int _minPayloadBytes = 130; // two-byte `fixlen_word`

void main() {
  final root =
      decodeVectorJson(File('assets/test_vectors.json').readAsStringSync())
          as Map;

  final vectors = (root['vectors'] as List).cast<Map<String, dynamic>>();

  // Top-level blocks this file does not drive are read by their own suites
  // (`invalid_utf8` by invalid_utf8_test.dart, `sequence_growth` by
  // sequence_growth_test.dart); an unknown one is simply not looked at, so the
  // loader tolerates the file gaining blocks without failing or warning.
  test('vector file metadata', () {
    expect(root['format'], 'sofabuffers-test-vectors');
    expect(jInt(root['version']), 1);
    expect(vectors, isNotEmpty);
  });

  // Every check this file registers, counted as it is registered so the
  // inventory test at the bottom can report the total the run executed.
  var checks = 0;
  void check(String name, dynamic Function() body) {
    checks++;
    test(name, body);
  }

  final skipVectors = vectors
      .where(
        (v) =>
            (v['skip_ids'] as List?) != null &&
            (v['skip_ids'] as List).isNotEmpty,
      )
      .toList();

  // The loader has no fixed-size bound anywhere -- and this is what would
  // notice if one appeared. It also pins the `requires` vocabulary: a token
  // this port cannot claim is a vector that must not be run silently.
  test('vector file is loaded whole (no silent truncation)', () {
    var maxSkipIds = 0;
    var maxFieldId = 0;
    var maxArrayElements = 0;
    var maxPayloadBytes = 0;
    var fp64Arrays = 0;
    final capabilities = <String>{};

    for (final v in vectors) {
      final rawSkipIds = (v['skip_ids'] as List?) ?? const [];
      final parsedSkipIds = rawSkipIds.map(jInt).toList();
      // The parsed list keeps every entry the file carries: no cap, no
      // dropped tail. (The C harness's MAXSKIP truncated here.)
      expect(
        parsedSkipIds.length,
        rawSkipIds.length,
        reason: v['name'] as String,
      );
      if (parsedSkipIds.length > maxSkipIds) maxSkipIds = parsedSkipIds.length;
      capabilities.addAll(
        ((v['requires'] as List?) ?? const []).cast<String>(),
      );

      for (final f in (v['fields'] as List).cast<Map<String, dynamic>>()) {
        final op = f['op'] as String;
        if (op != 'sequence_end') {
          final id = jInt(f['id']);
          if (id > maxFieldId) maxFieldId = id;
        }
        if (op == 'array') {
          final values = f['values'] as List<dynamic>;
          if (values.length > maxArrayElements) {
            maxArrayElements = values.length;
          }
          if (f['element_type'] == 'fp64') fp64Arrays++;
        }
        if (op == 'string') {
          final n = utf8.encode(f['value'] as String).length;
          if (n > maxPayloadBytes) maxPayloadBytes = n;
        }
        if (op == 'blob') {
          final n = (f['value_hex'] as String).length ~/ 2;
          if (n > maxPayloadBytes) maxPayloadBytes = n;
        }
      }
    }

    expect(maxSkipIds, greaterThanOrEqualTo(_minSkipIdsPerVector));
    expect(maxFieldId, greaterThanOrEqualTo(_minFieldId));
    expect(maxArrayElements, greaterThanOrEqualTo(_minArrayElements));
    expect(maxPayloadBytes, greaterThanOrEqualTo(_minPayloadBytes));
    expect(fp64Arrays, greaterThan(0));
    expect(
      capabilities.difference(_supportedCapabilities),
      isEmpty,
      reason:
          'a vector requires a capability this port does not implement; '
          'it must be gated, not run silently',
    );
    expect(skipVectors, isNotEmpty);
  });

  group('vectors', () {
    for (final v in vectors) {
      final name = v['name'] as String;
      final group = v['group'] as String;
      final offset = jInt(v['offset']);
      final fields = v['fields'] as List<dynamic>;
      final expectedHex = (v['serialized'] as Map)['hex'] as String;
      final skipIds = ((v['skip_ids'] as List?) ?? const []).map(jInt).toSet();

      // 1. Vector encode — replay fields, assert bytes == serialized.hex.
      check('$group/$name · encode', () {
        final bytes = encodeFields(fields, offset: offset);
        expect(bytesToHex(bytes), expectedHex);
      });

      // Chunked encode — a buffer far smaller than the message, driving the
      // flush callback repeatedly; concatenated output must match one-shot.
      // The first size is the port's declared `minOutputBuffer` (CORELIB_PLAN
      // §7.2 item 4): the smallest streaming buffer it accepts must already
      // produce the one-shot bytes.
      check('$group/$name · chunked-encode', () {
        for (final bufSize in [sofab.minOutputBuffer, 3, 7]) {
          final out = BytesBuilder(copy: true);
          final enc = sofab.Encoder(out.add, buffer: Uint8List(bufSize));
          replay(enc, fields);
          enc.flush();
          expect(
            bytesToHex(out.toBytes()),
            expectedHex,
            reason: 'bufSize=$bufSize',
          );
        }
      });

      // Sink-less encode — the same vector into a caller-supplied buffer sized
      // exactly to the message (plus its start offset) with **no** flush sink:
      // no minimum applies, the buffer holds the message and `written` hands it
      // back byte-identical. One byte short must report buffer-full rather than
      // truncate — the encoder never returns partial output as complete
      // (CORELIB_PLAN §5.1).
      check('$group/$name · sink-less encode', () {
        final expected = hexToBytes(expectedHex);
        final buf = Uint8List(offset + expected.length);
        final enc = sofab.Encoder.overBuffer(buf, offset: offset);
        replay(enc, fields);
        enc.flush();
        expect(bytesToHex(enc.written), expectedHex);

        if (expected.isNotEmpty) {
          final tight = sofab.Encoder.overBuffer(
            Uint8List(offset + expected.length - 1),
            offset: offset,
          );
          expect(
            () {
              replay(tight, fields);
              tight.flush();
            },
            throwsA(
              isA<sofab.SofabException>().having(
                (e) => e.code,
                'code',
                sofab.SofabError.bufferFull,
              ),
            ),
          );
        }
      });

      // 2. Vector decode — feed serialized.hex, assert recovered fields match.
      check('$group/$name · decode', () {
        final rec = RecordingVisitor();
        final status = sofab.Decoder.decode(hexToBytes(expectedHex), rec);
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // Chunked decode — one byte at a time must equal all-at-once, and so must
      // every chunk size in between. The sizes matter: a byte-at-a-time feed of
      // a `List<int>` and a multi-byte `Uint8List` take different paths through
      // `feed` — only the latter reaches the bulk payload move (corelib-dart#43),
      // and only a payload straddling a chunk boundary exercises the seam.
      check('$group/$name · chunked-decode', () {
        final bytes = hexToBytes(expectedHex);
        final rec = RecordingVisitor();
        final dec = sofab.Decoder(rec);
        var status = sofab.DecodeStatus.complete;
        for (final b in bytes) {
          status = dec.feed([b]);
        }
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));

        for (final size in const [2, 3, 5, 16, 4096]) {
          final rec2 = RecordingVisitor();
          final dec2 = sofab.Decoder(rec2);
          var st = sofab.DecodeStatus.complete;
          for (var i = 0; i < bytes.length; i += size) {
            final end = i + size < bytes.length ? i + size : bytes.length;
            st = dec2.feed(Uint8List.sublistView(bytes, i, end));
          }
          expect(st, sofab.DecodeStatus.complete, reason: 'chunk size $size');
          expect(
            rec2.events,
            expectedEvents(fields),
            reason: 'chunk size $size',
          );
        }
      });

      // 3. Roundtrip — encode → decode → compare.
      check('$group/$name · roundtrip', () {
        final bytes = encodeFields(fields);
        final rec = RecordingVisitor();
        final status = sofab.Decoder.decode(bytes, rec);
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // Skip-ids — leave the named ids unread at every level; the rest must
      // still decode and the message must be fully consumed.
      if (skipIds.isNotEmpty) {
        // The expectation is computed from the same op list with the skipped
        // ids (and any sub-sequence they open) removed, so a skip that eats one
        // byte too few or too many leaves the decoder inside the field and the
        // *next* field's value comparison fails. `expectSkipped` additionally
        // refuses a vacuous run: the skip must have removed something, and no
        // skipped id may reach the visitor.
        void expectSkipped(RecordingVisitor rec, {String? reason}) {
          final expected = expectedEventsSkipping(fields, skipIds);
          expect(
            expected.length,
            lessThan(expectedEvents(fields).length),
            reason: 'vector declares skip_ids but skips nothing',
          );
          expect(rec.events, expected, reason: reason);
          for (final id in skipIds) {
            // Event keys are `KIND:id:...`, except the bare `END` marker.
            final surfaced = rec.events.any((e) {
              final parts = e.split(':');
              return parts.length > 1 && parts[1] == '$id';
            });
            expect(
              surfaced,
              isFalse,
              reason: 'id $id was declined but still surfaced${reason ?? ''}',
            );
          }
        }

        check('$group/$name · skip-ids', () {
          final rec = RecordingVisitor(skipIds: skipIds);
          final status = sofab.Decoder.decode(hexToBytes(expectedHex), rec);
          expect(status, sofab.DecodeStatus.complete);
          expectSkipped(rec);
        });

        // The same decode fed one byte at a time: every skip then has to
        // survive a chunk boundary in the middle of the length word, the
        // payload and the sequence it walks over.
        check('$group/$name · skip-ids chunked', () {
          final bytes = hexToBytes(expectedHex);
          final rec = RecordingVisitor(skipIds: skipIds);
          final dec = sofab.Decoder(rec);
          var status = sofab.DecodeStatus.complete;
          for (final b in bytes) {
            status = dec.feed([b]);
          }
          expect(status, sofab.DecodeStatus.complete);
          expectSkipped(rec, reason: ' (one byte per chunk)');
        });
      }
    }
  });

  // CORELIB_PLAN §7.2: the run has to say how much of the shared suite it
  // actually executed, so a file that silently shrank (or a scenario that
  // stopped registering) is visible in the log rather than only in a diff.
  test('vector suite inventory', () {
    final byGroup = <String, int>{};
    for (final v in vectors) {
      byGroup.update(v['group'] as String, (n) => n + 1, ifAbsent: () => 1);
    }
    stdout.writeln(
      '[vectors] ${vectors.length} vectors, '
      '${skipVectors.length} with skip_ids '
      '(skip/matrix ${byGroup['skip/matrix'] ?? 0}, skip ${byGroup['skip'] ?? 0}) '
      '-> $checks checks executed',
    );
    // Every vector ran the six unconditional scenarios, and every vector with
    // `skip_ids` ran the two skip scenarios on top.
    expect(checks, vectors.length * 6 + skipVectors.length * 2);
  });
}

/// Replays a vector's `fields` through an existing encoder (for the chunked
/// path, where we drive the streaming API directly rather than the one-shot
/// convenience).
void replay(sofab.Encoder e, List<dynamic> fields) {
  for (final f in fields.cast<Map<String, dynamic>>()) {
    switch (f['op'] as String) {
      case 'unsigned':
        e.writeUnsigned(jInt(f['id']), jU(f['value']));
        break;
      case 'signed':
        e.writeSigned(jInt(f['id']), jU(f['value']));
        break;
      case 'boolean':
        e.writeBool(jInt(f['id']), f['value'] as bool);
        break;
      case 'fp32':
        e.writeFp32(jInt(f['id']), jF(f['value']));
        break;
      case 'fp64':
        e.writeFp64(jInt(f['id']), jF(f['value']));
        break;
      case 'string':
        e.writeString(jInt(f['id']), f['value'] as String);
        break;
      case 'blob':
        e.writeBlob(jInt(f['id']), hexToBytes(f['value_hex'] as String));
        break;
      case 'array':
        final id = jInt(f['id']);
        final et = f['element_type'] as String;
        final values = f['values'] as List<dynamic>;
        if (et == 'fp32') {
          e.writeFp32Array(id, values.map(jF).toList());
        } else if (et == 'fp64') {
          e.writeFp64Array(id, values.map(jF).toList());
        } else if (et.startsWith('u')) {
          e.writeUnsignedArray(id, values.map(jU).toList());
        } else {
          e.writeSignedArray(id, values.map(jU).toList());
        }
        break;
      case 'sequence_begin':
        e.beginSequenceLazy(jInt(f['id']));
        break;
      case 'sequence_end':
        e.endSequenceKeep();
        break;
    }
  }
}
