import 'dart:io';
import 'dart:typed_data';

import 'package:sofa_buffers_corelib/sofa_buffers_corelib.dart' as sofab;
import 'package:test/test.dart';

import 'vector_support.dart';

/// Drives the shared, language-agnostic conformance suite
/// (`assets/test_vectors.json`, generated by and copied from `corelib-c-cpp`).
///
/// This port supports the full wire format (no feature-disable), so per the
/// vectors README it **ignores `requires` and runs every vector**.
///
/// **Which column this repo asserts:** every check below uses `serialized` —
/// the dense, primitive-layer ground truth: exactly the bytes the raw
/// encoder/decoder API produces and consumes for the vector's op list. Each
/// vector also carries a `serialized_sparse` column, and **no test here reads
/// it, by design**: it is the MESSAGE_SPEC §2 sparse form, which only a message
/// layer can produce — the layer that knows each field's declared default and
/// therefore which fields (and which all-default sequences) to omit. A corelib
/// has no message layer; it is handed ops and writes them. `serialized_sparse`
/// is consumed by the **generator's** conformance drivers
/// (`tests/conformance/<lang>/` in `sofa-buffers/generator`), which generate a
/// message layer from the schema and compare its output against that column.
void main() {
  final root =
      decodeVectorJson(File('assets/test_vectors.json').readAsStringSync())
          as Map;

  final vectors = (root['vectors'] as List).cast<Map<String, dynamic>>();

  test('vector file metadata', () {
    expect(root['format'], 'sofabuffers-test-vectors');
    expect(jInt(root['version']), 1);
    expect(vectors, isNotEmpty);
  });

  group('vectors', () {
    for (final v in vectors) {
      final name = v['name'] as String;
      final group = v['group'] as String;
      final offset = jInt(v['offset']);
      final fields = v['fields'] as List<dynamic>;
      final expectedHex = (v['serialized'] as Map)['hex'] as String;
      final skipIds = ((v['skip_ids'] as List?) ?? const []).map(jInt).toSet();

      // 1. Vector encode — replay fields, assert bytes == serialized.hex.
      test('$group/$name · encode', () {
        final bytes = encodeFields(fields, offset: offset);
        expect(bytesToHex(bytes), expectedHex);
      });

      // Chunked encode — a buffer far smaller than the message, driving the
      // flush callback repeatedly; concatenated output must match one-shot.
      // The first size is the port's declared `minOutputBuffer` (CORELIB_PLAN
      // §7.2 item 4): the smallest streaming buffer it accepts must already
      // produce the one-shot bytes.
      test('$group/$name · chunked-encode', () {
        for (final bufSize in [sofab.minOutputBuffer, 3, 7]) {
          final out = BytesBuilder(copy: true);
          final enc = sofab.Encoder(out.add, buffer: Uint8List(bufSize));
          replay(enc, fields);
          enc.flush();
          expect(
            bytesToHex(out.toBytes()),
            expectedHex,
            reason: 'bufSize=$bufSize',
          );
        }
      });

      // Sink-less encode — the same vector into a caller-supplied buffer sized
      // exactly to the message (plus its start offset) with **no** flush sink:
      // no minimum applies, the buffer holds the message and `written` hands it
      // back byte-identical. One byte short must report buffer-full rather than
      // truncate — the encoder never returns partial output as complete
      // (CORELIB_PLAN §5.1).
      test('$group/$name · sink-less encode', () {
        final expected = hexToBytes(expectedHex);
        final buf = Uint8List(offset + expected.length);
        final enc = sofab.Encoder.overBuffer(buf, offset: offset);
        replay(enc, fields);
        enc.flush();
        expect(bytesToHex(enc.written), expectedHex);

        if (expected.isNotEmpty) {
          final tight = sofab.Encoder.overBuffer(
            Uint8List(offset + expected.length - 1),
            offset: offset,
          );
          expect(
            () {
              replay(tight, fields);
              tight.flush();
            },
            throwsA(
              isA<sofab.SofabException>().having(
                (e) => e.code,
                'code',
                sofab.SofabError.bufferFull,
              ),
            ),
          );
        }
      });

      // 2. Vector decode — feed serialized.hex, assert recovered fields match.
      test('$group/$name · decode', () {
        final rec = RecordingVisitor();
        final status = sofab.Decoder.decode(hexToBytes(expectedHex), rec);
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // Chunked decode — one byte at a time must equal all-at-once, and so must
      // every chunk size in between. The sizes matter: a byte-at-a-time feed of
      // a `List<int>` and a multi-byte `Uint8List` take different paths through
      // `feed` — only the latter reaches the bulk payload move (corelib-dart#43),
      // and only a payload straddling a chunk boundary exercises the seam.
      test('$group/$name · chunked-decode', () {
        final bytes = hexToBytes(expectedHex);
        final rec = RecordingVisitor();
        final dec = sofab.Decoder(rec);
        var status = sofab.DecodeStatus.complete;
        for (final b in bytes) {
          status = dec.feed([b]);
        }
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));

        for (final size in const [2, 3, 5, 16, 4096]) {
          final rec2 = RecordingVisitor();
          final dec2 = sofab.Decoder(rec2);
          var st = sofab.DecodeStatus.complete;
          for (var i = 0; i < bytes.length; i += size) {
            final end = i + size < bytes.length ? i + size : bytes.length;
            st = dec2.feed(Uint8List.sublistView(bytes, i, end));
          }
          expect(st, sofab.DecodeStatus.complete, reason: 'chunk size $size');
          expect(
            rec2.events,
            expectedEvents(fields),
            reason: 'chunk size $size',
          );
        }
      });

      // 3. Roundtrip — encode → decode → compare.
      test('$group/$name · roundtrip', () {
        final bytes = encodeFields(fields);
        final rec = RecordingVisitor();
        final status = sofab.Decoder.decode(bytes, rec);
        expect(status, sofab.DecodeStatus.complete);
        expect(rec.events, expectedEvents(fields));
      });

      // Skip-ids — leave the named ids unread at every level; the rest must
      // still decode and the message must be fully consumed.
      if (skipIds.isNotEmpty) {
        test('$group/$name · skip-ids', () {
          final rec = RecordingVisitor(skipIds: skipIds);
          final status = sofab.Decoder.decode(hexToBytes(expectedHex), rec);
          expect(status, sofab.DecodeStatus.complete);
          expect(rec.events, expectedEventsSkipping(fields, skipIds));
        });

        test('$group/$name · skip-ids chunked', () {
          final bytes = hexToBytes(expectedHex);
          final rec = RecordingVisitor(skipIds: skipIds);
          final dec = sofab.Decoder(rec);
          var status = sofab.DecodeStatus.complete;
          for (final b in bytes) {
            status = dec.feed([b]);
          }
          expect(status, sofab.DecodeStatus.complete);
          expect(rec.events, expectedEventsSkipping(fields, skipIds));
        });
      }
    }
  });
}

/// Replays a vector's `fields` through an existing encoder (for the chunked
/// path, where we drive the streaming API directly rather than the one-shot
/// convenience).
void replay(sofab.Encoder e, List<dynamic> fields) {
  for (final f in fields.cast<Map<String, dynamic>>()) {
    switch (f['op'] as String) {
      case 'unsigned':
        e.writeUnsigned(jInt(f['id']), jU(f['value']));
        break;
      case 'signed':
        e.writeSigned(jInt(f['id']), jU(f['value']));
        break;
      case 'boolean':
        e.writeBool(jInt(f['id']), f['value'] as bool);
        break;
      case 'fp32':
        e.writeFp32(jInt(f['id']), jF(f['value']));
        break;
      case 'fp64':
        e.writeFp64(jInt(f['id']), jF(f['value']));
        break;
      case 'string':
        e.writeString(jInt(f['id']), f['value'] as String);
        break;
      case 'blob':
        e.writeBlob(jInt(f['id']), hexToBytes(f['value_hex'] as String));
        break;
      case 'array':
        final id = jInt(f['id']);
        final et = f['element_type'] as String;
        final values = f['values'] as List<dynamic>;
        if (et == 'fp32') {
          e.writeFp32Array(id, values.map(jF).toList());
        } else if (et == 'fp64') {
          e.writeFp64Array(id, values.map(jF).toList());
        } else if (et.startsWith('u')) {
          e.writeUnsignedArray(id, values.map(jU).toList());
        } else {
          e.writeSignedArray(id, values.map(jU).toList());
        }
        break;
      case 'sequence_begin':
        e.beginSequenceLazy(jInt(f['id']));
        break;
      case 'sequence_end':
        e.endSequenceKeep();
        break;
    }
  }
}
